nelmio_cors:
  defaults:
    origin_regex: true
    # Regex des origines autorisées (localhost en dev, URL Vercel en prod)
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: ['content-type', 'authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/': ~
