<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma initial PostgreSQL (Neon). Remplace les anciennes migrations MySQL.
 */
final class Version20261008090521 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial PostgreSQL (Neon)';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Migration prévue pour PostgreSQL.');

        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE battle (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              description TEXT NOT NULL,
              source_url TEXT DEFAULT NULL,
              image TEXT DEFAULT NULL,
              slug VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              location_id_id INT DEFAULT NULL,
              winner_clan_id_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_13991734918DB72 ON battle (location_id_id)');
        $this->addSql('CREATE INDEX IDX_13991734B2E29111 ON battle (winner_clan_id_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE clan (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              description TEXT NOT NULL,
              founded_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              disbanded_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              image TEXT DEFAULT NULL,
              slug VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              leader_id_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9FF6A30CEFE6DECF ON clan (leader_id_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE favorite (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              entity_type VARCHAR(255) NOT NULL,
              entity_id INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_68C58ED99D86650F ON favorite (user_id_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE location (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              region VARCHAR(255) NOT NULL,
              latitude NUMERIC(10, 7) NOT NULL,
              longitude NUMERIC(10, 7) NOT NULL,
              type VARCHAR(255) DEFAULT NULL,
              description TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE samourai (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              birth_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              death_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              description TEXT NOT NULL,
              source_url TEXT DEFAULT NULL,
              image TEXT DEFAULT NULL,
              slug VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              clan_id_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_86289DD9E07BE140 ON samourai (clan_id_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE samourai_weapon (
              samourai_id INT NOT NULL,
              weapon_id INT NOT NULL,
              PRIMARY KEY (samourai_id, weapon_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_36208E4C154397A4 ON samourai_weapon (samourai_id)');
        $this->addSql('CREATE INDEX IDX_36208E4C95B82273 ON samourai_weapon (weapon_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE samourai_style (
              samourai_id INT NOT NULL,
              style_id INT NOT NULL,
              PRIMARY KEY (samourai_id, style_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_251C1A53154397A4 ON samourai_style (samourai_id)');
        $this->addSql('CREATE INDEX IDX_251C1A53BACD6074 ON samourai_style (style_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE samourai_battle (
              samourai_id INT NOT NULL,
              battle_id INT NOT NULL,
              PRIMARY KEY (samourai_id, battle_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4C8A3E9E154397A4 ON samourai_battle (samourai_id)');
        $this->addSql('CREATE INDEX IDX_4C8A3E9EC9732719 ON samourai_battle (battle_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE style (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              description TEXT NOT NULL,
              image TEXT DEFAULT NULL,
              slug VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE timeline (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              year INT NOT NULL,
              date DATE NOT NULL,
              title VARCHAR(255) NOT NULL,
              type VARCHAR(255) NOT NULL,
              description TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              battle_id_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_46FEC666667FCFE5 ON timeline (battle_id_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE timeline_entities (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              entity_type VARCHAR(255) NOT NULL,
              entity_id INT NOT NULL,
              timeline_id_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_DC3FEE5F2A1311 ON timeline_entities (timeline_id_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE weapon (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(255) NOT NULL,
              type VARCHAR(255) NOT NULL,
              description TEXT NOT NULL,
              image TEXT DEFAULT NULL,
              slug VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              battle
            ADD
              CONSTRAINT FK_13991734918DB72 FOREIGN KEY (location_id_id) REFERENCES location (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              battle
            ADD
              CONSTRAINT FK_13991734B2E29111 FOREIGN KEY (winner_clan_id_id) REFERENCES clan (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              clan
            ADD
              CONSTRAINT FK_9FF6A30CEFE6DECF FOREIGN KEY (leader_id_id) REFERENCES samourai (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              favorite
            ADD
              CONSTRAINT FK_68C58ED99D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai
            ADD
              CONSTRAINT FK_86289DD9E07BE140 FOREIGN KEY (clan_id_id) REFERENCES clan (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai_weapon
            ADD
              CONSTRAINT FK_36208E4C154397A4 FOREIGN KEY (samourai_id) REFERENCES samourai (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai_weapon
            ADD
              CONSTRAINT FK_36208E4C95B82273 FOREIGN KEY (weapon_id) REFERENCES weapon (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai_style
            ADD
              CONSTRAINT FK_251C1A53154397A4 FOREIGN KEY (samourai_id) REFERENCES samourai (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai_style
            ADD
              CONSTRAINT FK_251C1A53BACD6074 FOREIGN KEY (style_id) REFERENCES style (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai_battle
            ADD
              CONSTRAINT FK_4C8A3E9E154397A4 FOREIGN KEY (samourai_id) REFERENCES samourai (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              samourai_battle
            ADD
              CONSTRAINT FK_4C8A3E9EC9732719 FOREIGN KEY (battle_id) REFERENCES battle (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              timeline
            ADD
              CONSTRAINT FK_46FEC666667FCFE5 FOREIGN KEY (battle_id_id) REFERENCES battle (id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              timeline_entities
            ADD
              CONSTRAINT FK_DC3FEE5F2A1311 FOREIGN KEY (timeline_id_id) REFERENCES timeline (id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE battle DROP CONSTRAINT FK_13991734918DB72');
        $this->addSql('ALTER TABLE battle DROP CONSTRAINT FK_13991734B2E29111');
        $this->addSql('ALTER TABLE clan DROP CONSTRAINT FK_9FF6A30CEFE6DECF');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED99D86650F');
        $this->addSql('ALTER TABLE samourai DROP CONSTRAINT FK_86289DD9E07BE140');
        $this->addSql('ALTER TABLE samourai_weapon DROP CONSTRAINT FK_36208E4C154397A4');
        $this->addSql('ALTER TABLE samourai_weapon DROP CONSTRAINT FK_36208E4C95B82273');
        $this->addSql('ALTER TABLE samourai_style DROP CONSTRAINT FK_251C1A53154397A4');
        $this->addSql('ALTER TABLE samourai_style DROP CONSTRAINT FK_251C1A53BACD6074');
        $this->addSql('ALTER TABLE samourai_battle DROP CONSTRAINT FK_4C8A3E9E154397A4');
        $this->addSql('ALTER TABLE samourai_battle DROP CONSTRAINT FK_4C8A3E9EC9732719');
        $this->addSql('ALTER TABLE timeline DROP CONSTRAINT FK_46FEC666667FCFE5');
        $this->addSql('ALTER TABLE timeline_entities DROP CONSTRAINT FK_DC3FEE5F2A1311');
        $this->addSql('DROP TABLE battle');
        $this->addSql('DROP TABLE clan');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE samourai');
        $this->addSql('DROP TABLE samourai_weapon');
        $this->addSql('DROP TABLE samourai_style');
        $this->addSql('DROP TABLE samourai_battle');
        $this->addSql('DROP TABLE style');
        $this->addSql('DROP TABLE timeline');
        $this->addSql('DROP TABLE timeline_entities');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE weapon');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
