ServerName localhost

<VirtualHost *:${PORT}>
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride None
        Require all granted
        FallbackResource /index.php
    </Directory>

    # Transmet l'en-tête Authorization (JWT) à PHP
    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined
</VirtualHost>
